name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #- name: Build with Maven
    #  run: mvn -B -e -U clean install --file pom.xml
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"
        
        git-release-bot-name: "Untitled"
        git-release-bot-email: "cphms@outlook.com"
        
        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        maven-args: "-B -e -U clean install--file pom.xml"
